{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentreasury.serviceAccountName" . }}
  labels:
    {{- include "opentreasury.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
